import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: project1Laptop,
    transitionImage: project1Mobile,
    title: "A",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "B",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
  {
    id: 3,
    image: project3Laptop,
    transitionImage: project3Mobile,
    title: "C",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
  {
    id: 4,
    image: project4Laptop,
    transitionImage: project4Mobile,
    title: "D",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
  {
    id: 5,
    image: project5Laptop,
    transitionImage: project5Mobile,
    title: "E",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
  {
    id: 6,
    image: project6Laptop,
    transitionImage: project6Mobile,
    title: "F",
    codeLink: "https://github.com/nishant-19041",
    liveLink: "https://github.com/nishant-19041",
  },
];
